version: "2"
services:
  pg_red:
     hostname: pg_red
     build: ./master
     ports:
         - "5445:5432"
     volumes:
         #- pg_red_data:/var/lib/postgresql/data
         - shared_opt:/opt/pg_cluster
     environment:
         - POSTGRES_USER=wiwwo
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_red
     networks:
         - bridge-docker
     restart: always
     healthcheck:
         test: [ "CMD", "/bin/su", "postgres", "-c", "/check-new-master.sh" ]
         interval: 10s
         retries: 0
         start_period: 10s
  pg_green:
     hostname: pg_green
     build: ./slave
     depends_on:
         - pg_red
     ports:
         - "5446:5432"
     volumes:
         #- pg_green_data:/var/lib/postgresql/data
         - shared_opt:/opt/pg_cluster
     environment:
         - POSTGRES_USER=wiwwo
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_green
     networks:
         - bridge-docker
     restart: always
     healthcheck:
         #test: [ "CMD", "/bin/su", "postgres", "-c", "/docker-entrypoint-initdb.d/set-new-master.sh", "GO" ]
         test: [ "CMD", "/bin/su", "postgres", "-c", "/check-new-master.sh" ]
         interval: 10s
         retries: 0
         start_period: 10s
  pg_blue:
     hostname: pg_blue
     build: ./slave
     depends_on:
         - pg_red
     ports:
         - "5447:5432"
     volumes:
         #- pg_blue_data:/var/lib/postgresql/data
         - shared_opt:/opt/pg_cluster
     environment:
         - POSTGRES_USER=wiwwo
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_blue
     networks:
         - bridge-docker
     restart: always
     healthcheck:
         #test: [ "CMD", "/bin/su", "postgres", "-c", "/docker-entrypoint-initdb.d/set-new-master.sh", "GO" ]
         test: [ "CMD", "/bin/su", "postgres", "-c", "/check-new-master.sh" ]
         interval: 10s
         retries: 0
         start_period: 10s
volumes:
  #pg_red_data:
  #pg_green_data:
  #pg_blue_data:
  shared_opt:
networks:
  bridge-docker:
